import QuantumChannelContinuity.FoundationsWeakTesting
import QuantumChannelContinuity.FoundationsSingularLimits
import QuantumChannelContinuity.FoundationsInfiniteLimit

#print axioms QuantumChannelContinuity.stateRenyi_dataProcessing
#print axioms QuantumChannelContinuity.stateRelative_dataProcessing
#print axioms QuantumChannelContinuity.stateRenyi_nonneg
#print axioms QuantumChannelContinuity.stateRelative_nonneg
#print axioms QuantumChannelContinuity.stateRenyi_ne_top_iff
#print axioms QuantumChannelContinuity.stateRelative_ne_top_iff
#print axioms QuantumChannelContinuity.stateRenyi_tendsto_one_faithful
#print axioms QuantumChannelContinuity.POVM.channel
#print axioms QuantumChannelContinuity.POVM.channel_apply_basis_probability
#print axioms QuantumChannelContinuity.measured_sandwichedQuasi
#print axioms QuantumChannelContinuity.umegaki_common_eigenbasis
#print axioms QuantumChannelContinuity.measured_renyi_lower
#print axioms QuantumChannelContinuity.measured_relative_lower
#print axioms QuantumChannelContinuity.stateHockey_renyi_bound
#print axioms QuantumChannelContinuity.stateHockey_relative_bound

#print axioms QuantumChannelContinuity.hasDerivAt_quasi_one_common_eigenbasis
#print axioms QuantumChannelContinuity.stateRenyi_tendsto_one_common_eigenbasis
#print axioms QuantumChannelContinuity.stateRenyi_tendsto_one_common_eigenbasis_left

#print axioms QuantumChannelContinuity.exists_test_of_not_support
#print axioms QuantumChannelContinuity.stateRenyi_tendsto_top_left_of_test
#print axioms QuantumChannelContinuity.stateRenyi_tendsto_top_left_of_not_support
